name: aichatbot
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter_gemini: ^2.0.5
  google_mobile_ads: ^5.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  flutter_email_sender: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: 

flutter:
  uses-material-design: true
  assets:
    - assets/
